# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(b'UNPAID', b'Unpaid'), (b'PAID', b'Paid'), (b'PENDING', b'Payment Pending')], default=b'UNPAID', max_length=20),
        ),
    ]
