# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid',
            new_name='paid_at',
        ),
    ]
