# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20181113_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('fid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='disabled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(b'UNPAID', b'Unpaid'), (b'PAID', b'Paid'), (b'PENDING', b'Payment Pending'), (b'INVALID_AMOUNT', b'Invalid Amount Paid'), (b'ERROR', b'Processing Error')], default=b'UNPAID', max_length=20),
        ),
    ]
