# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20181114_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('fid',)},
        ),
        migrations.AddField(
            model_name='payment',
            name='fid',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Account'),
            preserve_default=False,
        ),
    ]
