# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20181114_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
