# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20181114_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='external_id',
            new_name='transaction_id',
        ),
    ]
