# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20181114_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
