# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20181114_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
