# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
