# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_payment_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fau',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[(b'GENERIC', b'GENERIC'), (b'KFS', b'KFS Invoice')], default=b'GENERIC', max_length=20),
        ),
    ]
